backend:
  name: git-gateway
  branch: master

media_folder: "images"

collections:
  - name: "works" # Used in routes, e.g., /admin/collections/blog
    label: "Works" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Priority", name: "priority", widget: "number"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Background Image", name: "background-image", widget: "image"}
      - {label: "Categories", name: "categories", widget: "list", default: ["works"]}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Personal Page'
        name: 'personal'
        file: '_pages/topics.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - {label: "Excerpt", name: "excerpt", widget: "string"}
          - {label: "Background Image", name: "background-image", widget: "image"}
          - { label: 'Body', name: 'body', widget: 'markdown' }
      # - label: 'Portfolio Page'
      #   name: 'works'
      #   file: '_pages/topics.md'
      #   fields:
      #     - { label: 'Title', name: 'title', widget: 'string' }
      #     - {label: "Excerpt", name: "excerpt", widget: "string"}
      #     - {label: "Background Image", name: "background-image", widget: "image"}
  - name: 'settings'
    label: 'Site settings'
    editor:
      preview: false
    files:
      - label: 'Settings'
        name: 'config'
        file: '_data/data.yml'
        fields:
          - { label: 'Website title', name: 'title', widget: 'string' }
          - { label: "Front page subtitle", name: "description", widget: "string"}
          - { label: "Front page contact me text", name: "closing-para", widget: "string"}
          - { label: 'Resume file', name: 'resume-file', widget: 'file' }